sudo: required
dist: trusty

language: java
services:
  - docker

env:
  global:
    - secure: "WBt8okocJt73D6rEnz0pfAK7Uluy7yDwYdyPs8iweJLxPa5AdKklahkOrnMG06DqRX4l4X1qh82Xe9DeboqfRhLm4zhH1vxX34XjGJ0lKJLameKNlm4i7ZUMK7axoITr+iHFapv6DaHN8OxzXP+aG5oIGqJxg+UIMJYGDOMdHwwRtnP1wNkI8BMhf8f0l5aUXwlW/JpjCmvEv7Vgxkjkp6BOTBbyTpR8mqzwbI4+lKKQxoZ/pPvdALhjxxR5adWWyGei4uR+oXA090pN9L4n1cObQwlzEb19IOxPKhiUOsotdvnGsRulbgmp8ip7J7OGdZTjcekGG+K5zCxgR/Cc9Fz+lfQpcv6/wsngHp/SszUltc79YHY35rhw6MKsxCY4YtTspjdvMOslqeulJAr/8ZmWrqx6TgRNlVHE3fokwdI7rvADzIZ9g1jk5+NWG3s6ifDo14bgrhCRlQWRoeQYuzsCOKzAwZNj5vXbUFaXhnqdqY42mU9X9WVURzH801mr/p5PO0y94i1op7F90HqV8PN2+i1mO1VGPP+IhLA1fSkNt+6h0MIOWRtsW0afiqQyt2ZKDQpOMFbv0nspZJkePPj9pZGpnExjQ7f4hz1Gs5gZF3pzfuJiD6t9xSvxm1HGda64r93+xUI54+SC0WDoNBQ+nEo4Rtik1nBN/s2f7/I="

# manage the caches here https://travis-ci.org/hawkular/hawkular-services/caches
cache:
  directories:
  - $HOME/.m2/repository

jdk:
- oraclejdk8

notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change

install:
- bash .travis.install.maven.sh "3.3.9" "${HOME}/mvn-home"
- export M2_HOME=${HOME}/mvn-home
- export PATH=${HOME}/mvn-home/bin:${PATH}
- mvn -version -B
# unshallow is needed by license-maven-plugin
- git fetch origin --unshallow || true

script:
- mvn -s .travis.maven.settings.xml verify -Pitest -Dfailsafe.useFile=false | grep -vF "[INFO] Downloading:" | grep
  -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0

after_success:
- bash .travis.hawkular-client.ruby.sh

before_cache:
# Clean the cached directories once their size exceeds the space left on the partition.
# This is important because Travis zips the chached directories to a temporary file on the same partition.
# Note that while we consider the summed size of all cached dirs, we remove only those ones that tend to grow over time
- CACHED_DIRECTORIES=("$HOME/.m2/repository")
- availBytes=$(df -P . | tail -1 | awk '{print $4}')
- cachedBytes=$(du -cs "${CACHED_DIRECTORIES[@]}" | tail -1 | awk '{print $1}')
- echo "Checking if the size of directories to cache ${cachedBytes} Bytes exceeds the free space ${availBytes} Bytes left on the current partition"
- if [ "${cachedBytes}" -gt "${availBytes}" ] ; then
    echo "Cleaning the cached dirs (${cachedBytes} Bytes) because their size exceeds the free space (${availBytes} Bytes) left on the current partition"
    rm -Rf "$HOME/.m2"
  fi
